# Generated by Django 4.2.4 on 2023-12-18 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Le nom de la section', max_length=64, null=True, verbose_name='Nom')),
                ('posted', models.BooleanField(default=False, help_text='posted_help_text', verbose_name='posted')),
                ('score', models.IntegerField(default=0, help_text='score_help_text', verbose_name='score')),
                ('user', models.ForeignKey(help_text='user_of_bot_help_text', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'bot',
                'verbose_name_plural': 'bots',
                'db_table': 'bot',
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movements', models.TextField(blank=True, help_text='movements_help_text', max_length=1024, null=True, verbose_name='movements')),
                ('result', models.BooleanField(default=False, help_text='result_help_text', verbose_name='result')),
                ('bot_left', models.ForeignKey(help_text='bot_left_of_match_help_text', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_left', to='game.bot', verbose_name='bot_left')),
                ('bot_right', models.ForeignKey(help_text='bot_right_of_match_help_text', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_right', to='game.bot', verbose_name='bot_right')),
            ],
            options={
                'verbose_name': 'match',
                'verbose_name_plural': 'matchs',
                'db_table': 'match',
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
