# Generated by Django 4.2.4 on 2024-01-11 14:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='error_messages_left',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1024, null=True), null=True, size=None), help_text='stderr_left_help_text', null=True, size=None, verbose_name='stderr_left'),
        ),
        migrations.AddField(
            model_name='match',
            name='error_messages_right',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1024, null=True), null=True, size=None), help_text='stderr_right_help_text', null=True, size=None, verbose_name='stderr_right'),
        ),
        migrations.AddField(
            model_name='match',
            name='output_left',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1024, null=True), help_text='output_left_help_text', null=True, size=None, verbose_name='output_left'),
        ),
        migrations.AddField(
            model_name='match',
            name='output_right',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1024, null=True), help_text='output_right_help_text', null=True, size=None, verbose_name='output_right'),
        ),
    ]
