# Generated by Django 4.2.4 on 2024-01-16 09:34

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0002_match_error_messages_left_match_error_messages_right_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bot',
            options={'ordering': ['-created_at', '-updated_at'], 'verbose_name': 'Bot', 'verbose_name_plural': 'Bots'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-created_at', '-updated_at'], 'verbose_name': 'Match', 'verbose_name_plural': 'Matchs'},
        ),
        migrations.AddField(
            model_name='match',
            name='scoreChangeLeft',
            field=models.IntegerField(default=0, help_text='score_change_left_help_text', verbose_name='score_change_left'),
        ),
        migrations.AddField(
            model_name='match',
            name='scoreChangeRight',
            field=models.IntegerField(default=0, help_text='score_change_right_help_text', verbose_name='score_change_right'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='posted',
            field=models.BooleanField(default=False, help_text='Le bot est-il public ou non', verbose_name='Publié'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='score',
            field=models.IntegerField(default=0, help_text='Le score du bot', verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='user',
            field=models.ForeignKey(help_text='Le créateur du bot', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='match',
            name='bot_left',
            field=models.ForeignKey(help_text="L'un des bots d l'affrontement", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_left', to='game.bot', verbose_name='Bot gauche'),
        ),
        migrations.AlterField(
            model_name='match',
            name='bot_right',
            field=models.ForeignKey(help_text="L'autre bot de l'affrontement", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_right', to='game.bot', verbose_name='Bot droit'),
        ),
        migrations.AlterField(
            model_name='match',
            name='error_messages_left',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1024, null=True), null=True, size=None), help_text="La sortie d'erreur du bot de gauche", null=True, size=None, verbose_name="Sortie d'erreur gauche"),
        ),
        migrations.AlterField(
            model_name='match',
            name='error_messages_right',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1024, null=True), null=True, size=None), help_text="La sortie d'erreur du bot de droite", null=True, size=None, verbose_name="Sortie d'erreur droite"),
        ),
        migrations.AlterField(
            model_name='match',
            name='movements',
            field=models.TextField(blank=True, help_text='Les mouvements des bots', max_length=1024, null=True, verbose_name='Mouvements'),
        ),
        migrations.AlterField(
            model_name='match',
            name='output_left',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1024, null=True), help_text="L'output du bot de gauche", null=True, size=None, verbose_name='Output gauche'),
        ),
        migrations.AlterField(
            model_name='match',
            name='output_right',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1024, null=True), help_text="L'output du bot de droite", null=True, size=None, verbose_name='Output droit'),
        ),
        migrations.AlterField(
            model_name='match',
            name='result',
            field=models.BooleanField(default=False, help_text="L'issue du match'", verbose_name='Résultat'),
        ),
    ]
