# Generated by Django 4.2.4 on 2024-01-16 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_bot_options_alter_match_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='scoreChangeLeft',
            new_name='score_change_left',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='scoreChangeRight',
            new_name='score_change_right',
        ),
    ]
