# Generated by Django 4.2.4 on 2023-11-28 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='title_help_text', max_length=50, verbose_name='title')),
                ('post', models.TextField(help_text='post_help_text', max_length=4096, verbose_name='post')),
                ('section', models.CharField(help_text='section_help_text', max_length=50, verbose_name='section')),
                ('views', models.PositiveIntegerField(help_text='views_help_text', verbose_name='views')),
                ('deleted', models.BooleanField(default=False, help_text='deleted_help_text', verbose_name='deleted')),
                ('user', models.ForeignKey(help_text='user_of_topic_help_text', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'topic',
                'verbose_name_plural': 'topics',
                'db_table': 'topic',
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
