# Generated by Django 4.2.4 on 2023-11-29 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicSection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default=False, help_text='code_help_text', max_length=64, verbose_name='Code')),
                ('name', models.CharField(default=False, help_text='deleted_help_text', max_length=64, verbose_name='deleted')),
                ('description', models.TextField(default=False, help_text='description_help_text', max_length=4096, verbose_name='description')),
            ],
            options={
                'verbose_name': 'topic_section',
                'verbose_name_plural': 'topic_sections',
                'db_table': 'topic_section',
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='topic',
            name='post',
        ),
        migrations.AddField(
            model_name='topic',
            name='content',
            field=models.TextField(blank=True, help_text='content_help_text', max_length=4096, null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(blank=True, help_text='title_help_text', max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='views',
            field=models.PositiveIntegerField(default=0, help_text='views_help_text', verbose_name='views'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, help_text='content_help_text', max_length=4096, null=True, verbose_name='content')),
                ('deleted', models.BooleanField(default=False, help_text='deleted_help_text', verbose_name='deleted')),
                ('topic', models.ForeignKey(help_text='topic_of_post_help_text', on_delete=django.db.models.deletion.PROTECT, to='forum.topic', verbose_name='topic')),
                ('user', models.ForeignKey(help_text='user_of_post_help_text', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'db_table': 'post',
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='topic',
            name='section',
            field=models.ForeignKey(help_text='topic_section_of_topic_help_text', null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.topicsection', verbose_name='section'),
        ),
    ]
