# Generated by Django 4.2.4 on 2023-10-10 09:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='The username', max_length=50, null=True, verbose_name='username')),
                ('email', models.EmailField(help_text='The email', max_length=50, unique=True, verbose_name='email')),
                ('is_email_confirmed', models.BooleanField(default=False, help_text='is email confirmed user detail', verbose_name='is email confirmed')),
                ('is_tou_accepted', models.BooleanField(default=False, help_text='is tou accepted user detail', verbose_name='is tou accepted')),
                ('is_admin', models.BooleanField(default=False, help_text='is admin user detail', verbose_name='admin')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'user',
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
