# Generated by Django 4.2.4 on 2023-11-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='biography',
            field=models.CharField(help_text="Un message de présentation de l'utilisateur", max_length=60, null=True, verbose_name='Biographie'),
        ),
    ]
