# Generated by Django 4.2.4 on 2023-12-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text="Le nom utilisé par l'utilisateur", max_length=50, null=True, verbose_name="Nom d'utilisateur"),
        ),
    ]
